---
- name: Install UFW
  become: true
  apt:
    name: ufw
    state: present

- name: Configure UFW
  become: true
  ufw:
    state: enabled

- name: Deny all incoming connections by default
  become: true
  ufw:
    policy: deny
    direction: incoming

- name: Allow all outgoing connections by default
  become: true
  ufw:
    policy: allow
    direction: outgoing

- name: Allow incoming from Tailscale
  become: true
  ufw:
    rule: allow
    if_in: "tailscale0"

- name: Allow HTTP access from Cloudflare IPs
  become: true
  ufw:
    rule: allow
    from: "{{ item }}"
    port: http
    proto: tcp
  loop: "{{ cloudflare_range }}"

- name: Allow HTTP access from Cloudflare IPs
  become: true
  ufw:
    rule: allow
    from: "{{ item }}"
    port: https
    proto: tcp
  loop: "{{ cloudflare_range }}"
