name: Deployment 0x7f.dev

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"
          extended: true
      - name: Build
        run: hugo --minify
      - name: Connect to tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Transfer release
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./public/
          remote_path: ~/release/
          remote_host: ${{ secrets.SERVER_HOSTNAME }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
